### PR TITLE
fix: fix failing ENS resolver

### LINKED ISSUE #59: bug: ENS provider failing
There is some issue with ENS provider, test is failing, using `provider.getAvatar` seem to always return null.

### PR DESCRIPTION
**Pull request by wa0x6e**
fix #59

### CODE REVIEW

File: src/resolvers/ens.ts [hunk 1]
```diff
@@ -1,22 +1,11 @@
...
-}
-
-export default async function resolve(address) {
+export default async function resolve(address: string) {
   try {
     const provider = getProvider(1);
-    const name = await resolveName(address);
-    if (!name) return false;
-    const url = await provider.getAvatar(name);
+    const url = await provider.getAvatar(address);
```
Comment (ChaituVR) [inline src/resolvers/ens.ts:8]: This method always return null 🤔

**Review by ChaituVR — CHANGES_REQUESTED** [review]

File: src/resolvers/ens.ts (hunk 1 above)
Comment (wa0x6e) [reply src/resolvers/ens.ts:8]: Why do you think so ? The tests are passing, and it does return a correct url when image exists. What are you passing in the arg ?

function argument name is misleading, and should be `name` and not `address`, I will fix that

Comment (wa0x6e) [reply src/resolvers/ens.ts:8]: the resolver only accepts an ENS name as agument, and not an eth address. Should we also support that ?

Comment (wa0x6e) [reply src/resolvers/ens.ts]: In fact, this resolver will always get an ENS name as argument (https://github.com/snapshot-labs/stamp/blob/641daa145c4a3c542270468888073aa6d21c4f7f/src/utils.ts#L61)

Comment (ChaituVR) [reply src/resolvers/ens.ts]: so here is what i did to reproduce.

If i go here https://stamp.fyi/avatar/fabien.eth i see 
image
same as here https://app.ens.domains/fabien.eth

Then if i run this code, and go to http://localhost:3000/avatar/fabien.eth i see:
image

so i've added a `console.log(url);` in `line 9` - It returns `null`
and with previous changes also it is `null` 🙈

Comment (ChaituVR) [reply src/resolvers/ens.ts]: image
Here getAvatar is top of `resolver` not on top of `provider`. could be because of that, but i am not 100% sure

Comment (wa0x6e) [reply src/resolvers/ens.ts]: Ok, I pushed another fix, still getting nothing from Fabien.eth, but everything else is working

Test with:

- http://localhost:3000/avatar/ricmoo.eth
- http://localhost:3000/avatar/snowowl.eth

Issue with fabien.eth is that the avatar url is not a http link but an eip address (`eip155:1/erc1155:0x495f947276749Ce646f68AC8c248420045cb7b5e/61751686310106735452369515624497384717106902022558848289817630643456812515329`), making `getAvatar()` return false.

The fix is now returning the raw text, but still need a way to convert that eip155 address to an http one

Comment (wa0x6e) [reply src/resolvers/ens.ts]: Do you have some pointer on how to convert the eip155 address to some more conventional http or something else ?

**Review by ChaituVR — APPROVED** [review]
tAck
