### PR TITLE
fix: fix ENS avatar resolver when avatar is not HTTP

### LINKED ISSUE #76: Fix NFT profile pictures
Issue with fabien.eth is that the avatar url is not a http link but an eip address (`eip155:1/erc1155:0x495f947276749Ce646f68AC8c248420045cb7b5e/61751686310106735452369515624497384717106902022558848289817630643456812515329`), making `getAvatar()` return false.

The fix is now returning the raw text, but still need a way to convert that eip155 address to an http one

_Originally posted by @wa0x6e in https://github.com/snapshot-labs/stamp/pull/61#discussion_r1280689987_

### LINKED ISSUE #109: Not getting image for ENS values, it returns blockie icon

### PR DESCRIPTION
**Pull request by wa0x6e**
Fix #76
Fix #109 

Fix missing image on ENS name, when the avatar metadata is not starting by `http`.
This fix uses ENS own metadata resolver as fallback, as pointed out here https://github.com/snapshot-labs/stamp/issues/109#issuecomment-1798361605

### CODE REVIEW

File: src/resolvers/ens.ts [hunk 1]
```diff
@@ -10,9 +10,9 @@ export default async function resolve(name: string) {
       return false;
     }
 
-    const url = await ensResolver.getText('avatar');
+    let url = await ensResolver.getText('avatar');
     if (!url || !url.startsWith('http')) {
-      return false;
+      url = `https://metadata.ens.domains/mainnet/avatar/${name}`;
     }
```
Comment (ChaituVR) [inline src/resolvers/ens.ts:16]: Not important but there is a solarlint notice (I use) 
```
Prefer using an optional chain expression instead, as it's more concise and easier to read.sonarlint(typescript:S6582)
```
Maybe we can try this
```
url = url?.startsWith('http') ? url : `https://metadata.ens.domains/mainnet/avatar/${name}`;
```

File: src/resolvers/ens.ts [hunk 2]
```diff
@@ -10,9 +10,9 @@ export default async function resolve(name: string) {
       return false;
     }
 
-    const url = await ensResolver.getText('avatar');
+    let url = await ensResolver.getText('avatar');
     if (!url || !url.startsWith('http')) {
-      return false;
+      url = `https://metadata.ens.domains/mainnet/avatar/${name}`;
```
Comment (ChaituVR) [inline src/resolvers/ens.ts:15]: Not sure if there is some rate limit 😄 but we can try

**Review by ChaituVR — APPROVED** [review]
tAck

File: src/resolvers/ens.ts (hunk 2 above)
Comment (wa0x6e) [reply src/resolvers/ens.ts:15]: We're using this as fallback, only on NFT image, should be fine

File: src/resolvers/ens.ts (hunk 1 above)
Comment (wa0x6e) [reply src/resolvers/ens.ts]: Done
